# Generated by Django 4.1.1 on 2022-10-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='user',
        ),
    ]
